source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "3.2.2"

gem "rails", "~> 7.0.4", ">= 7.0.4.3"
gem "pg", "~> 1.1"
gem "oj"
gem 'active_model_serializers'
gem "puma", "~> 5.0"
gem "jbuilder"
gem "redis", "~> 4.0"
gem "bcrypt", "~> 3.1.7"
gem "tzinfo-data", platforms: %i[ mingw mswin x64_mingw jruby ]
gem "bootsnap", require: false
gem "rack-cors"
gem "devise", "~> 4.9"
gem "devise-jwt", "~> 0.11.0"
gem "pundit", "~> 2.3"
gem "awesome_print", "~> 1.9"

group :development, :test do
  gem 'dotenv-rails'
  gem 'byebug'
  gem 'pry'
  gem 'pry-byebug'
  gem 'pry-rescue'
  gem 'pry-stack_explorer'
  gem 'pry-rails'
  gem 'rspec-rails'
  gem 'rubocop', require: false
  gem 'rubocop-rails'
  gem 'rubocop-rspec'
  gem 'guard'
  gem 'guard-rspec'
  gem 'guard-rubocop'
  gem 'vcr'
end

group :development do
  gem 'annotate'
  gem 'web-console'
  gem 'letter_opener'
  gem 'spring'
  gem 'spring-commands-rspec'
  gem 'rack-mini-profiler'
  gem 'flamegraph'
  gem 'stackprof'
end

group :test do
  # TBD
end
